name: learning-stencil
arguments: {
  description: "Stencil Learning Service",
  reportingTeam: "Stencil Learners",
  greetings: ["welcome", "goodbye"]
}
# Below is a list of modules to use for this application
# It should follow the following format:
# - name: <moduleImportPath>
#   version: "optional-version-to-pin-to"
modules:
  - name: github.com/getoutreach/stencil-base
  - name: github.com/Saddham/learning-stencil-module
replacements:
  github.com/Saddham/learning-stencil-module: /Users/spathan/Projects/learning-stencil-module
  github.com/Saddham/learning-stencil-native-extension: /Users/spathan/Projects/learning-stencil-native-extension